from enum import Enum


class EventTypeEnum(Enum):
    """
    The event types that can occur during operation.
    """
    TASK_LIST_MODIFIED = "TASK_LIST_MODIFIED"
    ADD_TASK_DIALOG_REQUESTED = "ADD_TASK_DIALOG_REQUESTED"
    EDIT_TASK_DIALOG_REQUESTED = "EDIT_TASK_DIALOG_REQUESTED"
    COMPLETED_TASK_DIALOG_REQUESTED = "COMPLETED_TASK_DIALOG_REQUESTED"
    SAVE_REQUESTED = "SAVE_REQUESTED"
